# Generated by Django 6.0 on 2025-12-31 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=20)),
                ('priority_level', models.CharField(choices=[('High', 'high'), ('Medium', 'medium'), ('Low', 'low')], default='Low', max_length=10)),
            ],
        ),
    ]
