# Generated by Django 6.0 on 2026-01-01 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_task_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('assigned_tasks', models.ManyToManyField(blank=True, to='manager.task')),
            ],
        ),
    ]
