# Generated by Django 6.0 on 2026-01-01 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_worker'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='assigned_worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.worker'),
        ),
    ]
