# Generated by Django 6.0 on 2026-01-01 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_task_assigned_worker'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date_created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
